[package]
name = "Renderer_release"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb="0.27"
nalgebra-glm = "0.18.0"
tobj = "4.0.2"
rand = "0.8.5"
fastnoise-lite = "1.1.1"
once_cell = "1.20.2"
image = "0.25.4"